[directories]
# The directory containing images
img_directory = "demo/input"
# the output directory
output_directory = "demo/output"

[minimal]
# Minimal requirements - if these are not met the image is skipped
width = 1800
height = 1000
# these arucos ids must be found
aruco_ids = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

[[box]]
# turquoise crayon handwritten text "hello"
# choose exactly four aruco ids that surround the area in a clockwise fashion, i.e. top left followed by top right, bottom right, and finally bottom left
aruco_ids = [6, 11, 10, 5]   
# specify the corners (each aruco marker has four) of above aruco markers ('tl' = top left, 'tr' = top right, 'br' = bottom right, 'bl' = bottom left)                
corners = ['bl', 'tl', 'tr', 'br']   
# width of the output image in pixels        
output_width = 500
# height of the output image in pixels
output_height = 350

[[box]]
# red crayon handwritten text "arucutter"
aruco_ids = [1, 6, 5, 0]
corners = ['bl', 'tl', 'tr', 'br']
output_width = 500
output_height = 350

[[box]]
# cute tiger button
aruco_ids = [13, 12, 7, 8]
corners = ['tl', 'tr', 'br', 'bl']
output_width = 360
output_height = 500

[[box]]
# intentionally flipped (mirrored) box containing two objects 
# take care when specifying the order of the corners and enter in clockwise fashion, see above
aruco_ids = [6, 7, 2, 1]
corners = ['tr', 'tl', 'bl', 'br']
output_width = 360
output_height = 500



