[project]
name = "arucutter"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Johannes Elias", email = "joheli@gmx.net" }
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.13.0.92",
    "pydantic>=2.12.5",
    "rich>=14.3.3",
    "typer>=0.24.1",
]

[project.scripts]
arucutter = "arucutter.cli:cli"

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"
