[project]
name = "arucutter"
version = "0.1.3"
description = "Arucutter segments images based on ArUco markers."
readme = "README.md"
authors = [
    { name = "Johannes Elias", email = "joheli@gmx.net" }
]
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.13.0.92",
    "pydantic>=2.12.5",
    "rich>=14.3.3",
    "typer>=0.24.1",
]

[project.urls]
homepage = "https://github.com/joheli/arucutter" 

[project.scripts]
arucutter = "arucutter.cli:cli"

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ptpython>=3.0.32",
]

[tool.pytest.ini_options]
testpaths = [
  "tests",
]
